# Assessorias

<center>

```{r,echo=F, fig.width=4, fig.height=3, fig.align='center', warning=F,message=F}
library(plotly)
library(dplyr)
dados=data.frame(Frequência=c(14,44,61,30),
                 Ano= c("2018","2019","2020","2021"))
plot_ly(data = dados) %>%
  add_trace(x = ~ Ano,
            y = ~ Frequência,
            type = "bar",
            mode = "lines+markers",
            name = "Assessorias",
            marker=list(color=c("red","blue","green","yellow"))) %>%
  layout(yaxis = list(title="Frequência de assessorias"))
```

```{r,echo=F, fig.width=4, fig.height=3, fig.align='center', warning=F,message=F}
dados=data.frame(Frequência=c(9,140),
                 Área= c("Outras","Agronomia"))
plot_ly(data = dados) %>%
  add_trace(x = ~ Área,
            y = ~ Frequência,
            type = "bar",
            mode = "lines+markers",
            name = "Áreas",
            marker=list(color=c("blue","green")))%>%
  layout(yaxis = list(title="Frequência de Áreas de atuação"))
```

```{r,echo=F, fig.width=4, fig.height=3,fig.align='center', warning=F,message=F}
library(plotly)
library(dplyr)
dados=data.frame(Frequência=c(1,3,3,1),
                 Ano= c("2018","2019","2020","2021"))
plot_ly(data = dados) %>%
  add_trace(x = ~ Ano,
            y = ~ Frequência,
            type = "bar",
            mode = "lines+markers",
            name = "Frequência de cursos",
            marker=list(color=c("red","blue","green")))%>%
  layout(yaxis = list(title="Frequência de cursos"))
```

</center>