# Projetos

## Projetos de Pesquisa

<br>

****

2021 - Atual

**ANÁLISE BIOQUÍMICA E DO TRANSCRIPTOMA DE FOLHAS E FRUTOS DE *Coffea eugenioides* PARA A IDENTIFICAÇÃO DE GENES CANDIDATOS RELACIONADOS A BIOSSÍNTESE DE DITERPENOS EM CAFEEIROS**

****

*Descrição*: O café é uma das bebidas mais consumidas no mundo e uma commodity importante para países de clima tropical, especialmente para o brasil. A qualidade da bebida esta diretamente ligada aos compostos bioquímicos presentes nos grãos. Os diterpenos são metabólitos especializados produzidos pelas plantas e diversos estudos relatam que esses compostos estão relacionados ao bom desenvolvimento das plantas e a sua capacidade de defesa contra insetos. Além disso, eles apresentam um alto potencial biotecnológico, inúmeras patentes já foram registradas, principalmente para a produção de fármacos e cosméticos. Os diterpenos cafestol (caf) e caveol (kah) são compostos exclusivos do gênero *Coffea* spp. A presença desses diterpenos em frutos e raízes pode indicar uma possível relação desses compostos tanto com os mecanismos de defesa das plantas, assim como nas características sensoriais da bebida (aroma e sabor). Apesar da sua importância, estudos que relacionem os mecanismos genéticos e bioquímicos envolvidos no processo de biossíntese de caf e kah são ainda incipientes, o que limita a nossa capacidade de compreender a importância ecológica, agronômica e industrial desses compostos. Estudos bioquímicos e moleculares desses compostos já foram realizados para a espécie tetraplóide *C. arabica*. Este projeto tem por objetivo determinar o perfil metabólico de caf e kah, analisar e validar o perfil transcricional de genes envolvidos no metabolismo de diterpenos em *C. eugenioides*, um dos parentais diploides que originou por hibridização natural a espécie *C. arabica*. O genoma de *C. eugenioides* (*Arabica coffee* genome consortium) será utilizado como referência para o alinhamento de sequências rnam (rna-seq/illumina) de dois tecidos (folha e fruto), esta análise será realizada com a ferramenta hisat2. O perfil de expressão gênica digital será obtido através da quantificação do número de sequencias alinhadas ao genoma de referência (kallisto software). Os genes diferencialmente expressos serão identificados com o software deseq2. Em paralelo, será realizada a extração e quantificação de caf e kah para folha e frutos. Genes candidatos serão escolhidos para a validação do seu perfil transcricional por rtq-pcr baseados na integração e análise dos dados bioquímicos e moleculares. O transcriptoma será integralmente anotado por análises comparativa contra as proteínas previamente depositadas em bancos de dados públicos (ncbi-nr, uniprotkb/swiisprot, interproscan, kegg) e isto será feito automaticamente pelo software blast2go. Os genes candidatos serão funcionalmente anotados manualmente. Os resultados deste estudo irão contribuir para aumentar a compreensão das bases moleculares e funções biológicas provenientes deste metabolismo especializado de cafeeiros. Este conhecimento será fundamental para a produção de plantas com teores desejáveis de diterpenos e irá auxiliar o programa de melhoramento genético de cafés com foco na qualidade nutracêutica da bebida.

**Coordenador**: Suzana Tiemi Ivamoto-Suzuki

<br><br>

****

2020 - Atual

FLUXO DE MASSA ENTRE CLASSES DE AGREGADOS DE SOLO ESTÁVEIS EM ÁGUA

****

Descrição: A associação positiva entre o teor de matéria orgânica e o tamanho médio de agregados estáveis em água é amplamente conhecido e aceito na literatura científica. Entretanto, pouco se sabe sobre a dinâmica de diferentes classes de tamanho de agregados estáveis em água, quando os teores de matéria orgânica variam. Essa lacuna existe, em parte, devido à dificuldade de se obter variações significativas do teor de matéria orgânica no solo, sem que outros fatores também interfiram na agregação. Nesse sentido, os solos oriundos de rochas ígneas, como as constituintes da formação Serra Geral, podem possibilitar a existência de uma situação ímpar para a quantificação desses fluxos de massa. Nesses solos, o isolamento do efeito da matéria orgânica sobre a agregação pode ser possível através da coleta de amostras em diferentes profundidades, uma vez que esses solos apresentam pequeno gradiente textural e mineralógico ao longo da porção superior do perfil, fatores que possuem elevada influência sobre a agregação.

**Coordenador**: THADEU RODRIGUES DE MELO

<br><br>

****

2018 - 2019

**MANEJO INTEGRADO DE PLANTAS DANINHAS EM POMAR CÍTRICO**

****

*Descrição*: A citricultura se configura como uma das principais atividades agrícolas nacional e, para tal efeito, demanda práticas sustentáveis como o manejo de plantas de cobertura nas entrelinhas do pomar, desempenhando papel no controle de plantas infestantes. Neste contexto, o objetivo deste trabalho será estimar valores de mulch (palhada de braquiárias) necessários para supressão da emergência da comunidade de plantas daninhas e das espécies predominantes em pomar cítrico. os tratamentos testados serão diferentes níveis de cobertura de palhada (mulch) de quatro espécies de braquiárias (*U. decumbens*, *U. ruziziensis*, *U. humidicola*, *U. brizantha*): 0,0 t ha-1; 1,5 t ha-1; 3,0 t ha-1; 4,5 t ha-1; 6,0 t ha-1 e 7,5 t ha-1. O delineamento utilizado será inteiramente casualizado, em esquema fatorial 4 x 6 (fator a: espécies de braquiárias; fator b: níveis de mulch - diferentes quantidades de biomassa seca das braquiárias), com quatro repetições. as avaliações iniciarão a partir de 7 dias após a instalação (DAI) do experimento e serão realizadas semanalmente, com a contagem e identificação de plantas daninhas emergidas, sem sua retirada. o procedimento se repetirá até os 42 DAI. As relações entre os tratamentos serão descritas por meio de regressões lineares e não-lineares e do teste da falta de-ajuste, sendo realizados com o pacote drc no R 3.2.2 (RITZ e STREIBIG 2014; R Development Core Team 2016)..

Coordenadora: CAMILLA DE ANDRADE PACHECO

****

2018 - 2018

ESPÉCIES DE UROCHLOA COMO PLANTAS DE COBERTURA EM POMAR DE LARANJA NATAL

****

*Descrição*: A crescente demanda por alimentos mais saudáveis, de melhor qualidade, com elevado valor nutricional e produzidos em sistemas menos agressivos ao ambiente gerou a necessidade do levantamento de informações técnicas que propiciem produções de frutos de citros, para o estado do paraná, com qualidade e que atendam à preservação ambiental. Visando a agricultura familiar, em especial o pequeno citricultor, estudos com manejos adequados da cobertura do solo para copa e porta-enxerto dos citros contribuirão, não só com o aumento da produção, mas também na redução dos reflexos negativos sobre as plantas cítricas e o ambiente, ocasionados pela ausência de cobertura vegetal na entrelinha, estimulando-se assim a permanência de pequenos produtores na citricultura. com este trabalho, objetiva-se avaliar o manejo na entrelinha do pomar de laranja natal utilizando cinco espécies de Urochloa (*U. brizantha*, *U. decumbens*, *U. dictyoneura*, *U. humidicola*, *U. ruziziensis*). O pomar foi implementado na fazenda escola da universidade estadual do paraná, município de Londrina/PR, em março de 2015, no espaçamento de 7 x 3 m, utilizando como copa a laranja natal e como porta-enxerto o citrumelo swingle. já a semeadura das espécies de urochloa será mecanizada e realizada em dezembro de 2016. Dessa forma, avaliar-se-ão a fitomassa da vegetação intercalar e porcentagem de cobertura do solo; decomposição da fitomassa e liberação de nutrientes; análises físico-químicas do solo (linha e entrelinha); análises microbiológicas do solo; levantamento fitossociológico e avaliação do banco de sementes das plantas daninhas; avaliação das plantas de laranja natal com análise química foliar e medida indireta de clorofila; e desenvolvimento vegetativo e produtivo das laranjeiras natal. Todos os dados serão submetidos à análise de variância e posterior teste de comparação de médias.

Coordenadora: CAMILLA DE ANDRADE PACHECO

<br><br>

****

2018 - Atual

**PLANEJAMENTO E ANÁLISE DE EXPERIMENTOS APLICADOS EM CIÊNCIAS AGRÁRIAS E BIOLÓGICAS**

****

*Descrição*: A condução e análise de experimentos devem ser realizados evitando que efeitos de fatores possivelmente controlados inflacionem a variação do acaso. Para isso, deve-se realizar o planejamento experimental detalhadamente, de maneira que isole os possíveis fatores controláveis e diminua o erro experimental. Há situação que o número de ensaios realizados no experimento é reduzido devido há algum empecilho, logo é necessário algumas técnicas para determinar o melhor delineamento experimental e análise estatística. Portanto, o objetivo do projeto é pesquisar diferentes delineamentos experimentais e suas respectivas análises, sendo aplicados em ciência agrárias e biológicas, com o auxilio do software R..

Coordenador: GUILHERME BIZ

****

2017 - 2018

***Trichoderma* spp. PARA CONTROLE BIOLÓGICO DE *Colletotrichum gloeosporioides* NA CULTURA DO ABACATEIRO E *Sclerotinia sclerotiorum* NA CULTURA DO TOMATEIRO**

****

*Descrição*: Fungos como *Trichoderma* spp. são utilizados como medida alternativa para o controle de doenças de plantas cultivadas. Dentre essas doenças, a antracnose (*Colletotrichum gloeosporioides*) na cultura do abacateiro e o mofo branco (*Sclerotinia sclerotiorum*) na cultura do tomateiro são responsáveis por grandes prejuízos. O objetivo deste trabalho será avaliar o potencial dos isolados de Trichoderma spp. em relação a sua capacidade de produção de metabólitos voláteis e não voláteis, inibidoras de *Colletotrichum gloeosporioides* e *Sclerotinia sclerotiorum*; e controle das doenças em condições de casa-de-vegetação. portanto, serão realizados oito testes para avaliar o potencial antagônico dos isolados de *Trichoderma* spp., pertencentes ao laboratório de fitopatologia da agronomia na UEL: dois testes de confrontação direta, um para cada fitopatógeno (*C. gloeosporioides* e *S. sclerotiorum*), dois testes de inibição do crescimento micelial com metabólitos voláteis, dois testes de inibição do crescimento micelial com metabólitos não voláteis, teste de controle pós-colheita de *Colletotrichum gloeosporioides* em frutos de abacate com filtrado de *Trichoderma* spp. e teste de controle do mofo branco na cultura do tomateiro com filtrados de *Trichoderma* spp..

Coordenador: CIRO HIDEKI SUMIDA

<br><br>

****

2017 - 2018

**CURVA DE CRESCIMENTO E MATURAÇÃO DA ROMÃ NO NORTE DO PARANÁ**

****

*Descrição*: A busca pela medicina alternativa tem despertado interesse de diversos estudiosos em vista das propriedades nutracêuticas das plantas medicinais. Diversas espécies têm sido visadas, dentre elas destaca-se a romã, que apresenta grande interesse quanto à suas propriedades medicinais, com destaque para a sua atividade antioxidante. Apesar da crescente importância do uso da romã em diferentes produtos farmacêuticos e cosméticos, o comportamento da fruta, quanto ao seu desenvolvimento e maturação ainda é desconhecido. O objetivo deste trabalho é determinar o ritmo de crescimento dos frutos de romã, a partir da antese até o ponto de colheita, além de determinar as propriedades químicas de romãs, da cultivar Valenciana. O experimento será realizado em pomar comercial instalado no município de Assaí-PR. Será realizada análise de regressão para o desenvolvimento do fruto e acúmulo das características organolépticas, como pH, teores de sólidos solúveis totais, acidez titulável e teores de vitamina C. Espera-se determinar o ponto adequado de colheita de frutos de romã, para que o produtor possa estimar quantos dias após a antese os frutos apresentarão as características desejáveis pelo mercado consumidor..

Coordenadora: Thaís Cristina Morais Vidal

<br><br>

****

2014 - 2016

**QUALIDADE DE FEIJÃO-VAGEM**

****

*Descrição*: O trabalho tem por objetivo avaliar a qualidade de plantas e sementes de diferentes linhagens de feijão-vagem (*Phaseolus vulgaris* L.). O experimento será conduzido na Universidade Estadual de Londrina (UEL), durante o período de 2013 a 2015 em casa de vegetação. Serão analisadas características físicas das plantas como florescimento, ciclo, altura da planta, altura de inserção da primeira vagem, comprimento e largura das vagens, número de vagens por planta, número de sementes por vagem, comprimento e largura das sementes, teor de água da semente no momento da colheita, massa seca das sementes, peso de mil sementes, posteriormente será feita a analise fisiológica das sementes com os testes de germinação, de vigor, porcentagem de emergência, índice de velocidade de emergência, altura da parte aérea da plântula, a massa seca das plântulas, teste de envelhecimento acelerado, a condutividade elétrica e teste de tetrazólio. Após os resultados os dados serão submetidos à análise de variância e as diferenças avaliadas pelo teste Tukey a 5%..

Coordenadora: LUCIA SADAYO ASSARI TAKAHASHI

## Projetos de extensão

****

2020 - Atual

**BRDATA: BRASIL EM DADOS**

****

*Descrição*: Desde os seus primórdios, os principais objetivos das universidades foram a produção, a transmissão e a perpetuação do conhecimento humanístico, científico e técnico. O modelo acadêmico perdura ao longo dos séculos devido ao seu sucesso na produção e difusão de conhecimento útil, capaz de modificar ambientes, populações e culturas. Os recursos humanos formados nas universidades são agentes da transformação, e as tecnologias nelas concebidas são meios para o desenvolvimento e o progresso. Apesar do conhecimento adquirido pela humanidade por meio das universidades, a maioria dos países, incluindo o brasil, enfrentam diariamente graves problemas de ordem econômica (como por exemplo a pobreza e o desemprego), social (como a fome, violência e desigualdade), de saúde pública (como doenças e epidemias), educacional (como a evasão escolar e qualidade no ensino) e ambiental (como as mudanças climáticas, poluição, desmatamentos). Em geral, boa parte do conhecimento científico está armazenado em bancos de dados inacessíveis ou bloqueados na forma de paywalls (método de restringir o acesso a um conteúdo por meio de pagamentos) ou restritos nos artigos científicos. Dessa forma, para compreender os problemas que afetam milhões de indivíduos, precisa-se obter dados provenientes de estudos que abordam essas questões. Somente assim, pode-se investigar as variáveis de interesse e tornar os resultados baseados em análises de dados acessíveis em uma plataforma compreensível e de domínio público. Para isso, torna-se necessário a utilização de métodos estatísticos que permitem obter informações científicas a partir de dados coletados no mundo real e que são essenciais para a tomada de decisão e o enfrentamento dos problemas centrais do brasil e do estado do paraná. Esse projeto tem por objetivo o desenvolvimento de uma plataforma (página na internet) aberta ao público e hospedada no domínio da universidade estadual de londrina, construída por meio do software estatístico R no ambiente markdown, com informações relevantes e acessíveis, de tópicos e indicadores relacionados ao brasil e seus estados federativos a partir da descrição, visualização, estudos de tendência, projeções e manipulação dos dados, que são ferramentas essenciais para a construção de uma sociedade mais justa e igualitária. Objetivo: - Informar a população do brasil e do estado do paraná sobre os indicadores na economia, saúde, educação, agricultura, meio ambiente por meio da análise de dados. População alvo: As populações alvo desse projeto são os cidadãos da cidade de londrina, do estado do paraná e do brasil, isto é, pessoas, órgãos públicos, estudantes, docentes, servidores, etc. Eles serão informados sobre os estudos de análise e previsão de dados até o final do primeiro ano do projeto..

Coordenador: RODRIGO ROSSETO PESCIM

****

2019 - Atual

**ASSESSORIA ESTATÍSTICA**

****

*Descrição*: Este projeto pretende atender a pesquisadores, estudantes e instituições públicas e privadas, sendo coordenado e executado pelos professores do departamento de estatística desta universidade, com auxílio de estagiários. O objetivo deste projeto de assessoria é a orientação da pesquisa científica em todas as suas etapas: dimensionamento de amostra, validação do instrumento de coleta de dados e análise de resultados estatísticos através de programas (softwares) específicos nas diversas áreas do conhecimento humano; ciências da saúde, ciências biológicas, ciências sociais aplicadas, ciências humanas e ciências exatas. Nesse sentido, a troca de experiências entre os professores, pesquisadores e alunos envolvidos é de suma importância, pois possibilita a verificação das teorias estatísticas aplicadas na prática de diferentes áreas do conhecimento. Do mesmo modo, busca-se esclarecer a população da importância da estatística para validação da pesquisa científica como um todo, elucidando a validação, os termos, os métodos e os testes estatísticos, assim como disponibilizar um site com conteúdos da área de estatística e do software R.

**Coordenadora**: MARIANA RAGASSI URBANO

****

2018 - Atual

**ESTATÍSTICA EXPERIMENTAL: EXEMPLOS E APLICAÇÕES COM UTILIZAÇÃO DO SOFTWARE R**

****

*Descrição*: Na análise de dados de experimentos, nas mais diversas áreas, invariavelmente é utilizado algum programa estatístico. Entre os inúmeros softwares disponíveis no mercado, tanto proprietário quanto livre, o r tem se tornado unanimidade entre os pesquisadores das universidades do mundo todo, por ser um software gratuito e de código fonte aberto. Muitos alunos, pesquisadores ou professores ainda não o utilizam devido a dificuldades na estruturação do programa para análise dos dados e dos comandos necessários para suas análises específicas. Sendo assim, a proposta deste projeto é construir uma página na internet, onde estarão disponíveis inúmeros exemplos de análise de dados dos experimentos nos diversos delineamentos estatísticos, e procurando abordar várias situações possíveis, como experimentos desbalanceados ou com parcelas perdidas, bem como um grande número de testes de comparações múltiplas e a utilização de contrastes. Os conjuntos de dados a serem utilizados serão de experimentos já conduzidos na Universidade Estadual de Londrina - UEL, bem como exemplos da literatura. Assim, na página html hospedada no domínio da UEL, constará a análise completa do conjunto de dados e suas opções de análise usando o R, transformando-se em uma página de consulta aos alunos, pesquisadores e professores do mundo todo..

**Coordenador**: SILVANO CESAR DA COSTA

## Projetos de ensino

****

2011 - Atual

**ANÁLISE DOS TRABALHOS DE CONCLUSÃO DE CURSOS REALIZADOS NO CURSO DE AGRONOMIA DA UNIVERSIDADE ESTADUAL DE LONDRINA.**

****

*Descrição*: O curso de agronomia da universidade estadual de londrina, criado em 1978, formou até o presente mais de 1.200 engenheiros agrônomos. a partir de sua implantação passou por modificações curriculares. A primeira, em 1985, teve como objetivo adequar o currículo ao mínimo definido pelo ministério da educação. A segunda, em 1992, quando a universidade estadual de londrina passou do sistema de matrícula por disciplinas para o regime seriado anual. na grade curricular do regime seriado anual, foi implantada a atividade de trabalho de conclusão de curso, onde na 5ª série são desenvolvidas atividades que culminam na apresentação de um trabalho perante uma banca examinadora. Em 1996, portanto, foram apresentados os primeiros trabalhos de conclusão de curso como requisito à avaliação à disciplina 3 AGR 021, atualmente 6 AGR 704. O objetivo deste projeto é realizar um levantamento dos trabalhos de conclusão de curso apresentados a partir de 1996, resgatar os trabalhos armazenados em diferentes locais (bibliotecas, orientadores) e colocar para consultas na sua integra com uma análise de acordo com a área/assunto e espécies escolhidas pelos alunos.

**Coordenadora**: LUCIA SADAYO ASSARI TAKAHASHI


# Minhas publicações

## Artigos

****

PAULA, J. C. B.; ROSALEM, I. B.; RIBEIRO JUNIOR, W. A.; SHIMIZU, G. D.; FARIA, R. T.; PACHECO, C. A.; OLIVEIRA JUNIOR, A. G. . Post-harvesting longevity of bird of paradise (*Strelitzia* spp.) treated with carnauba wax. *COMUNICATA SCIENTIAE*, v. 12, p. 1-8, 2021. [Acesse](https://www.comunicatascientiae.com.br/comunicata/article/view/3421)

****

FAZAM, J. C.; PASINI, A.; SHIMIZU, G. D.; ALMEIDA, J. C.. Mortality of leaf-cutting ants with salicylic acid. SEMINA. *CIÊNCIAS AGRÁRIAS (ONLINE)*, v. 42, p. 2599-2606, 2021. [Acesse](http://www.uel.br/revistas/uel/index.php/semagrarias/article/view/41565)

****

SHIMIZU, G. D.; PAULA, J. C. B.; NEVES, C. S. V. J.; PACHECO, C. A.. Quality of pomegranate peel cultivar Valenciana as determined by different drying methods. *Revista Brasileira de Fruticultura*, v. 42, p. 1-12, 2020. [Acesse](https://doi.org/10.1590/0100-29452020431)

****

SHIMIZU, G. D.; PAULA, J. C. B.; RIBEIRO, L. T. M.; RIBEIRO JUNIOR, W. A.; FANTIN, L. H.; SUMIDA, C. H.; PACHECO, C. A.. Control of spot on pomegranate fruit in field and phytosanitary quality during postharvest. *REVISTA BRASILEIRA DE CIENCIAS AGRARIAS*, v. 15, p. 1-6, 2020. [Acesse](https://doi.org/10.5039/agraria.v15i3a8218)

****

PAULA, J. C. B.; RIBEIRO JUNIOR, W. A.; SHIMIZU, G. D.; MEN, G. B.; FARIA, R. T.. Fertilizante de liberação controlada no crescimento inicial da orquídea *Phalaenopsis* spp.. *CULTURA AGRONOMICA (UNESP. ILHA SOLTEIRA)*, v. 29, p. 2, 2020. [Acesse](https://doi.org/10.32929/2446-8355.2020v29n2p289-299)

****

SHIMIZU, G. D.; OROZIMBO, R. F.; RIBEIRO, L. T. M.; HIGUCHI, M. T.; PAULA, J. C. B.; SUMIDA, C. H. . Substrate incubation time after fungi inoculation in the control tomato seedling damping-off. *SCIENTIA AGRARIA PARANAENSIS*, v. 19, p. 411-415, 2020. [Acesse](https://doi.org/10.18188/sap.v19i4.24609)

****

PAULA, J. C. B.; RIBEIRO JUNIOR, W. A.; SHIMIZU, G. D.; MEN, G. B.; FARIA, R. T.. Cryopreservation in liquid nitrogen of seeds of the orchid *brasilian Miltonia flavescens* Lindl.. *agro@mbiente on-line*, v. 14, p. 1-11, 2020. [Acesse]( http://dx.doi.org/10.18227/1982-8470ragro.v14i0.6388)

****

PAULA, J. C. B.; RIBEIRO JUNIOR, W. A.; SHIMIZU, G. D.; MEN, G. B.; PACHECO, C. A.; FARIA, R. T. Pós-colheita de folhas de espécies de *Strelitizia* spp. *REVISTA CULTURA AGRONÔMICA*, v. 29, p. 412-425, 2020. [Acesse](https://doi.org/10.32929/2446-8355.2020v29n4p412-425)

****

PACHECO, C. A.; SHIMIZU, G. D.; BASSETO, T.; COSTA, D. S.; NEVES, C. S. V. J.; AZEVEDO, F. A. Fremont IAC 543: uma alternativa para a produção de tangerinas. *REVISTA DE CIÊNCIAS AGRÁRIAS (LISBOA)*, v. 42, p. 1032-1039, 2019. [Acesse](https://revistas.rcaap.pt/rca/article/view/15330/14880)

****

HATA, F. T.; URSI, M. V.; PAULA, M. T.; SHIMIZU, G. D.; PAULA, J. C. B.; KUSSABA, D. A. O.; SOUSA, N. V. Intercropping garlic in strawberry fields improves land equivalent ratio and gross income. *CIÊNCIA RURAL*, v. 49, p. 1-8, 2019. [Acesse](https://doi.org/10.1590/0103-8478cr20190338)

****

BAUCHROWITZ, I. M.; HIGUCHI, M. T.; SHIMIZU, G. D.; SILVA, C. M.; OLIVEIRA, A. F. Phenological behavior and quality of fruits plum genotypes in the municipality of Ponta Grossa-PR. *Revista Brasileira de Tecnologia Aplicada nas Ciências Agrárias*, v. 12, p. 89-96, 2019. [Acesse](https://doi.org/10.5935/PAeT.V12.N2.08)

****

PACHECO, C. A.; SCHINOR, E. H.; AZEVEDO, F. A.; SHIMIZU, G. D.; BASTIANEL, M.; CRISTOFANI-YALY, M. Sensory acceptance and postharvest quality of a new hybrid of citrus: TMxLP 16. *Citrus Research & Technology*, v. 39, p. 1032-1039, 2018. [Acesse](http://dx.doi.org/10.4322/crt.08315)

****

KATO, D. S.; SILVA, C. M.; HIGUCHI, M. T.; BAUCHROWITZ, I. M.; SANTOS NETO, J.; SHIMIZU, G. D.; OLIVEIRA, A. F.. Produção de mudas de maracujá amarelo submetidos a doses crescentes de adubação de liberação lenta. *TERRA E CULTURA*, v. 34, p. 310-320, 2018. [Acesse](http://periodicos.unifil.br/index.php/Revistateste/article/view/510)

****

SHIMIZU, G. D.; VIDAL, T. C. M. . Dissimilaridade genética entre genótipos de romã oriundos do norte do Paraná. *Actas Portuguesas de Horticultura*, v. 29, p. 93, 2017. [Acesse](https://aph.aphorticultura.pt/wp-content/uploads/2019/10/dissimilaridade_gen%C3%A9tica_entre_gen%C3%B3tipos_de_rom%C3%A3_oriundos_do.pdf)

****

SUMIDA, C. H. ; SHIMIZU, G. D. ; CANTERI, M. G. ; GIGLIOTI, E. A. . Aplicação Rentável. *CULTIVAR GRANDES CULTURAS*, v. 199, p. 28-29, 2015.

****

## Trabalhos completos

****

DANTAS, A. A. ; HIGUCHI, M. T. ; RIBEIRO, L. T. M. ; SHIMIZU, G. D. ; COSTA, G. S. B. ; NOGUEIRA, A. F. ; SILVA, C. M. . EFEITO DO SUBSTRATO E APLICAÇÃO DE ÁCIDO INDOLBUTÍRICO (AIB) NO ENRAIZAMENTO DE GOIABEIRA PELO MÉTODO DE ALPORQUIA. In: **VIII Conferência Online - Agronomia**, 2020, Evento Virtual. Anais do VIII Conferência Online - Agronomia, 2020.

****

RIBEIRO, L. T. M. ; SHIMIZU, G. D. ; HIGUCHI, M. T. ; RIBEIRO JUNIOR, W. A. ; BINOTTO, C. ; DIAS, J. P. ; MARTINS, B. R. ; PUIA, J. D. ; SATO, A. J. . EXTRATO DE Cyperus rotundus L. NO ENRAIZAMENTO DE ESTACAS SEMILENHOSAS DE VIDEIRA BRS CARMEM. In: **VIII Conferência Online - Agronomia**, 2020, Evento Virtual. Anais da VIII Conferência Online - Agronomia, 2020.

****

SANTOS, L. M. G. ; FAVONI, V. A. ; SHIMIZU, G. D. ; CECCATTO, S. E. K. ; ARMACOLO, N. M. ; SANTOS, J. V. F. ; SAAB, O. J. G. A. ; RALISCH, R. . ATRIBUTOS FÍSICO- QUÍMICOS DO SOLO MODIFICADOS PELO CONSÓRCIO MILHO-Urochloa ruziziensis. In: **VIII Conferência Online - Agronomia**, 2020, Evento Virtual. Anais do VIII Conferência Online - Agronomia, 2020.

****

RIBEIRO JUNIOR, W. A. ; PIZZALUNGA, P. ; DIAS FILHO, P. J. ; PAULA, J. C. B. ; SHIMIZU, G. D. ; RIBEIRO, L. T. M. ; KOYAMA, R. ; FARIA, R. T. . CRESCIMENTO E DESENVOLVIMENTO DA BROMÉLIA Neoregelia Fireball EM DIFERENTES NÍVEIS DE SOMBREAMENTO. In: **VIII Conferência Online - Agronomia, 2020**, Evento Virtual. Anais do VIII Conferência Online - Agronomia, 2020.

****

SHIMIZU, G. D.; RIBEIRO, L. T. M. ; PAULA, J. C. B. ; HIGUCHI, M. T. ; RIBEIRO JUNIOR, W. A. ; SANTOS, L. M. G. ; MARUBAYASHI, R. Y. P. . PERDA DE MASSA, QUALIDADE VISUAL E TEMPO DE PRATELEIRA DE FRUTOS DE ROMÃ EM FUNÇÃO DE DIFERENTES TRATAMENTOS. In: **VIII Conferência Online - Agronomia**, 2020, Evento Virtual. Anais da VIII Conferência Online - Agronomia, 2020.

****

PAULA, J. C. B. ; RIBEIRO JUNIOR, W. A. ; SHIMIZU, G. D. ; PELLIZZARO, V. ; FARIA, R. T. . Germinação de Petunia x hybrida em diferentes substratos. In: **I Congresso Brasileiro Interdisciplinar de Ciência e Tecnologia**, 2020, Londrina. Anais do I Congresso Brasileiro Interdisciplinar de Ciência e Tecnologia, 2020.

****

HIGUCHI, M. T. ; PINHATA, A. A. ; SILVA, C. M. ; SHIMIZU, G. D. . CARACTERIZAÇÃO FÍSICO-QUÍMICA DE CULTIVARES DE BANANEIRA EM FUNÇÃO DO ESTÁDIO DE MATURAÇÃO. In: **VII Congresso Online - Agronomia**, 2019, Londrina. Anais do VII Congresso Online - Agronomia, 2019.

****

TONELLI, R. K. ; HIGUCHI, M. T. ; SUMIDA, C. H. ; MARUBAYASHI, R. Y. P. ; SHIMIZU, G. D. . EFEITO DE DICLOROISOCIANURATO DE SÓDIO SOBRE O DESENVOLVIMENTO E NODULAÇÃO DA SOJA. In: **VI Congresso Virtual Brasileiro de Agronomia**, 2018, Londrina. Anais do VI Congresso Virtual Brasileiro de Agronomia, 2018.

****

HIGUCHI, M. T. ; ANDRADE, V. F. ; SUMIDA, C. H. ; MARUBAYASHI, R. Y. P. ; SHIMIZU, G. D. . INOCULAÇÃO DE SEMENTES DE MILHO UTILIZANDO Trichoderma sp. COMO PROMOTOR DE CRESCIMENTO EM COMBINAÇÃO COM Azospirillum sp.. In: **VI Congresso Virtual Brasileiro de Agronomia**, 2018, Londrina. Anais do VI Congresso Virtual Brasileiro de Agronomia, 2018.

****

SHIMIZU, G. D.; COQUEIRO, A. C. P. ; PAULA, J. C. B. ; SUMIDA, C. H. ; PESTANA, J. K. ; HATA, F. T. ; SHIMIZU, D. K. ; HIGUCHI, M. T. . BIOESTIMULADOR NA GERMINAÇÃO E DESENVOLVIMENTO INICIAL DE MUDAS DE ROMÃ. In: **V Congresso Virtual Brasileiro de Agronomia**, 2017. Anais do V Congresso Virtual Brasileiro de Agronomia, 2017.

****